### ISSUE TITLE
Assessing the Pearson Correlation on the American Gut Data

### ISSUE THREAD

**Issue by EngineerDanny** [EngineerDanny/CS685-Microbe-Network-Research#1]
According to the SPIEC-EASI [research paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004226),  **Pearson’s correlation coefficient** is the standard tool to infer a network through correlation analysis among all pairs of OTU (Operational Taxonomic Unit) samples. From this method, an interaction between microbes is assumed when the absolute value of the correlation coefficient is sufficiently high.

The Pearson correlation coefficient (r) is a number from –1 to 1 that measures the strength and direction of the relationship between two variables. 

<img width="500" alt="Screenshot 2022-09-29 at 6 32 46 PM" src="https://user-images.githubusercontent.com/47421661/193170921-dc65df11-157c-4f05-9fa4-b4d7e5dd2dcf.png">

| Pearson correlation coefficient (r) | Correlation type     |
|-------------------------------------|----------------------|
| 0.7 - 1                      |  **Very Strong** Positive correlation |
| 0.4 - 0.69                     | Strong Positive correlation |
| 0 - 0.39                     | Weak - Moderate  Positive correlation |
| 0                                   | Neutral/Zero correlation  |
|  0 to –0.39                    | Weak - Moderate  Negative correlation |
|  -0.4 to –0.69                    | Strong Negative correlation |
|  -0.7 to –1                    | **Very Strong** Negative correlation |

**Comment by EngineerDanny** [comment]
@tdhock The code for testing is [here](https://github.com/EngineerDanny/CS685-Microbe-Network-Research/blob/main/Fall-2022/week-5/pearson-cor.R)

**Comment by EngineerDanny** [comment]
The new table is created after running the Pearson correlation method on the original datasets. This filters the datasets, giving out only the absolute **strong correlated**( ```|r| >= 0.7```) taxas.
<img width="262" alt="Screenshot 2022-09-30 at 7 42 58 PM" src="https://user-images.githubusercontent.com/47421661/193380035-2c2d3a35-0683-4312-9ca0-1771a5909db7.png">

This is the output of the code. I took one of the taxa-taxa relationship plots. This plot shows a very strong correlation between Taxa X292134 and Taxa X288710.
![Rplot](https://user-images.githubusercontent.com/47421661/193378701-a696edea-1fba-4409-ae3e-9cd31a595efc.png)

**Comment by tdhock** [comment]
that looks good, thanks for sharing. what is that line? is it regression line (asymmetric) or correlation line? (symmetric)
we should discuss about how to use the correlation to compute test error in the cross-validation / matrix completion setting.
one way to do it would be to use the average of values over correlation lines.
that is if there are P columns/taxa, and we have column j which is missing/test, you could use any of the other P-1 columns to infer/predict column j. So you could consider each of them, and then predict the average value over all the P-1 correlation lines.
We should also start thinking about multivariate methods like regularized regression https://en.wikipedia.org/wiki/Lasso_(statistics) and CCA https://en.wikipedia.org/wiki/Canonical_correlation

**Comment by EngineerDanny** [comment]
Yh that line is a correlation line.

**Comment by tdhock** [comment]
ok, you should compute the correlation line and plot it yourself, using geom_abline.

**Comment by EngineerDanny** [comment]
Sure. That is actually very helpful. I will try that and give you feedback.

**Comment by EngineerDanny** [comment]
@tdhock Just a quick question.  How do you suggest, I compute the `intercept` and `slope` in order to plot with the `geom_abline`.

**Comment by tdhock** [comment]
we discussed the formula on the board the other day, https://en.wikipedia.org/wiki/Correlation#Bivariate_normal_distribution

**Comment by EngineerDanny** [comment]
@tdhock  Yh. That works well. So quick review, I used the formular, 
<img width="300" alt="Screenshot 2022-10-05 at 6 27 44 PM" src="https://user-images.githubusercontent.com/47421661/194193554-2a904f42-c294-4ef5-81e8-c337f1d594ad.png">  
from https://en.wikipedia.org/wiki/Correlation#Bivariate_normal_distribution.
Rearranged it to the standard straight line formula, `Y = mX + c` where `m` is the gradient and `c` is the intercept.

Below is the correlation line between `Taxa X292134` and `Taxa X288710` plotted using the `geom_abline`. 

![Rplot01](https://user-images.githubusercontent.com/47421661/194195443-e12097e9-8421-4e42-b060-4715a55d8797.png)

It looks similar to the regression line shown in the [comment](https://github.com/EngineerDanny/CS685-Microbe-Network-Research/issues/1#issuecomment-1264208562) above, however, this time I have all the parameters (gradient and intercept of the line) needed to compute the accuracy/error of the method.

**Comment by tdhock** [comment]
great, m is called slope though (not gradient)

**Comment by EngineerDanny** [comment]
> great, m is called slope though (not gradient)

Sure

**Comment by EngineerDanny** [comment]
## Experiment 1
- The first experiment is to find out how the `test error` varies with the `number of samples` for the `Pearson Correlation` method. The last column is labeled as the output `y` and the rest of the columns are labeled as input `X`. The goal is to predict the output `y` using the input `X` and running it with different `# of Samples`.

- The `test error` is computed by taking the mean of the `mean_absolute_error`  of the predicted values compared to the actual test values.

**Comment by EngineerDanny** [comment]
- Dataset generated after running the test  : 

<img width="532" alt="Screenshot 2022-10-30 at 5 31 40 AM" src="https://user-images.githubusercontent.com/47421661/198904007-78a41d45-fcf8-416b-a985-a20bbc7107b5.png">

**Comment by EngineerDanny** [comment]
- The graph output is shown below :

![my_pearson_simple_facetted_2](https://user-images.githubusercontent.com/47421661/198903961-254d4b4e-0047-47c9-9a96-592f9a255109.png)

- It can be inferred from the graph above that `test_error` decreases as the `number of samples(rows)` increases. The value of the `test_error` ranges from 9 to 26.

**Comment by tdhock** [comment]
there is a problem with your ggplot code (missing group or facet).
Looks like there are several values of test_error for each value of # of samples. are those several values for different test folds? if so can you please add a fold ID column? Then plot the mean+/- SD over folds?

**Comment by EngineerDanny** [comment]
@tdhock Yes, they are for different test folds. I will need to rerun the tests with the fold ID column to the dataset.

**Comment by EngineerDanny** [comment]
- After fixing the issues mentioned above, this is graph output 
- Links : [Main code](https://github.com/EngineerDanny/CS685-Microbe-Network-Research/blob/main/Fall-2022/week-11/my_pearson_model_type_2.py), [Graph output script](https://github.com/EngineerDanny/CS685-Microbe-Network-Research/blob/main/Fall-2022/week-11/my_pearson_model_type_2_graph_script.ipynb)

![pearson_type_2_image](https://raw.githubusercontent.com/EngineerDanny/CS685-Microbe-Network-Research/main/Fall-2022/week-11/my_pearson_model_type_2_graph.png)

**Comment by tdhock** [comment]
why does it go up at the end?
